stages:
    - test
    - build
    - deploy_dev
    # - deploy_prod

variables:
    NGINX_IMAGE: $CI_REGISTRY_IMAGE/nginx-api:$CI_COMMIT_REF_NAME
    GUNICORN_IMAGE: $CI_REGISTRY_IMAGE/gunicorn-api:$CI_COMMIT_REF_NAME

test:
    image: docker:latest
    stage: test
    services:
        - docker:dind
    script:
        - docker build -f docker/dev/Dockerfile -t $GUNICORN_IMAGE .
        - docker run $GUNICORN_IMAGE inv test
    only:
        - /master|lappis-homolog|gitlab-ci/
    environment: test
    tags:
        - docker

build:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    script:
        - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
        - docker build -f docker/prod/Dockerfile_nginx -t $NGINX_IMAGE .
        - docker tag $NGINX_IMAGE $CI_REGISTRY_IMAGE/nginx-api:latest
        - docker push $NGINX_IMAGE
        - docker push $CI_REGISTRY_IMAGE/nginx-api:latest
        - docker build -f docker/prod/Dockerfile -t $GUNICORN_IMAGE .
        - docker tag $GUNICORN_IMAGE $CI_REGISTRY_IMAGE/gunicorn-api:latest
        - docker push $GUNICORN_IMAGE
        - docker push $CI_REGISTRY_IMAGE/gunicorn-api:latest
    only:
        - /master|lappis-homolog|gitlab-ci/
    tags:
        - docker

deploy_homolog:
    image: cdrx/rancher-gitlab-deploy
    stage: deploy_dev
    services:
        - docker:dind
    script:
        - upgrade --environment Development --stack SALIC-API --service gunicorn --new-image $GUNICORN_IMAGE --no-finish-upgrade --debug
        - upgrade --environment Development --stack SALIC-API --service nginx-api --new-image $NGINX_IMAGE --no-finish-upgrade --debug
    only:
        - /lappis-homolog|gitlab-ci/ # change to development branch only
    environment: development
    tags:
        - docker
