version: '3'
services:
  gunicorn:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_pyodbc

    volumes:
      - ./:/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_nginx

    ports:
      - "80:80"

    depends_on:
      - gunicorn
