version: '3'
services:
  gunicorn:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile

    environment:
        - SQL_DRIVER=pyodbc
        - DATABASE_HOST=192.168.10.250
        - DATABASE_USER=sa
        - DATABASE_PASSWORD=cd-graf005231
        - DATABASE_PORT=1433

    volumes:
      - ./:/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile_nginx

    ports:
      - "80:80"

    depends_on:
      - gunicorn
